services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: anderson
      POSTGRES_PASSWORD: anderson123456
      POSTGRES_DB: church
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql  # ← ÚNICA MUDANÇA AQUI
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anderson -d church"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: node:20
    container_name: membresia-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://anderson:anderson123456@postgres:5432/church
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5555:3000"
      - "5556:3001"
      - "5557:5556"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: sh -c "npm install && npx prisma db push && npx prisma generate && CHOKIDAR_USEPOLLING=true NEXT_WEBPACK_USEPOLLING=1 npm run dev"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge